require 'ruboty/munou/responders/base'
require 'ruboty/munou/responders/what_responder'
require 'ruboty/munou/responders/random_responder'
require 'ruboty/munou/responders/pattern_responder'
require 'ruboty/munou/responders/template_responder'
